# Generated by Django 2.1.5 on 2022-05-12 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220512_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='create_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='Dfautl', max_length=30),
            preserve_default=False,
        ),
    ]
