# Generated by Django 2.1.5 on 2022-05-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220512_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
