# Generated by Django 2.1.5 on 2022-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220512_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
