# Generated by Django 4.0.5 on 2022-06-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220512_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link_img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
