# Generated by Django 4.0.5 on 2022-06-30 12:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
