# Generated by Django 2.0.8 on 2022-05-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220510_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='user_pk',
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
